---
title: "3-results_render"
author: "Marcell Völler"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# to render this file, objects must be created using 2-results_summary.R or
# if these are saved locally, loaded in using 4-read_data.R

# run the line below to render document
#rmarkdown::render("3-results_render.Rmd", envir = globalenv())
```

# Descriptive tables

## No Hysteresis

```{r, results = "asis"}
summary(nohysteresis_table, text = TRUE, title = "No Hysteresis - Parameters")
```

```{r, results = "asis"}
summary(nohysteresis_vars_table, text = TRUE, title = "No Hysteresis - Variables")
```

## Hysteresis with External Change as Covariate

```{r, results = "asis"}
summary(extchange_table, text = TRUE, title = "External Change - Parameters")
```

```{r, results = "asis"}
summary(extchange_vars_table, text = TRUE, title = "External Change - Variables")
```

## Hysteresis with Aversive State as Covariate

```{r, results = "asis"}
summary(avstate_table, text = TRUE, title = "Aversive State - Parameters")
```

```{r, results = "asis"}
summary(avstate_vars_table, text = TRUE, title = "Aversive State - Variables")
```

# BICs of fitted models

```{r}
# bic_frame <- tibble("Fit" = c("1-state", "2-state_avstate", "2-state_avstate_hyst", "2-state_extchange", 
#                  "2-state_extchange_hyst", "3-state"),
#        "BIC" = c(hmm1s_bic, hmm2s_avstate_bic, hmm2s_avstatehyst_bic, hmm2s_extchange_bic, 
#                hmm2s_extchangehyst_bic, hmm3s_bic))
# bic_frame$BIC <- round(bic_frame$BIC)

bic_frame <- readRDS(file = "model_bic_values.rds")

options(scipen = 999)
plot(1:6, bic_frame$BIC, xlab = "Fit", ylab = "BIC", type = "b", xaxt = "n", cex.axis = 0.6, 
     las = 1, bty = "n", ylim = c(-50000,-100000))
axis(1, at = 1:6, labels = bic_frame$Fit, cex.axis = 0.555)

```

# Plots of Individual Phenomena

## Limit Cycle

```{r}
# set plot margins
par(mar = c(5, 5, 5, 7), xpd = TRUE)

# select data
cycle_data <- data %>%
  filter(pp_nr == 252) 

# get changepoint locations
cycle_cpts <- cpt_res[[253]]@cpts

# plot variables across time and set basic settings
plot(x = 0:40319, y = cycle_data$sui_thoughts, type = "l", xlab = "Time in Minutes", 
     ylab = "Value",main = "Limit Cycle (Simulation 253)", las = 1, cex.axis = 0.75, 
     bty = "l")
abline(v = cycle_cpts, col = "tomato", xpd = FALSE)
lines(cycle_data$stressor, col = "deepskyblue")
lines(cycle_data$av_state, col = "darkviolet")
lines(cycle_data$other_escape, col = "chartreuse")

# add legend
cycle_cols <- c("black","deepskyblue", "darkviolet", "chartreuse")
cycle_labels <- c("Suicidal Thoughts", "Stress", 
                  "Aversive State", "Other Escape Strategies")
legend("topright", inset = c(-0.31, 0.2), lty = 1, cex = 0.6, col = cycle_cols, 
       legend = cycle_labels, title = "Variables", bty = "n")
```

## Hysteresis

```{r}
# set plot margins
par(mar = c(5, 5, 5, 7), xpd = TRUE)

# select data
hyst_data <- data %>%
  filter(pp_nr == 633) 

# get changepoint locations
hyst_cpts <- cpt_res[[634]]@cpts

# plot variables across time and set basic settings
plot(x = 0:40319, y = hyst_data$sui_thoughts, type = "l", lwd = 2, xlab = "Time in Minutes", 
     ylab = "Value",main = "Hysteresis (Simulation 633)", las = 1, cex.axis = 0.75, 
     bty = "l", ylim = c(0, max(hyst_data$stressor)))
abline(v = hyst_cpts, col = "tomato", xpd = FALSE, lwd = 2)
lines(hyst_data$stressor, col = "deepskyblue")
lines(hyst_data$av_state, col = "darkviolet")
lines(hyst_data$other_escape, col = "chartreuse")

# add legend
legend("topright", inset = c(-0.31, 0.2), lty = 1, lwd = 2, cex = 0.6, col = cycle_cols, 
       legend = cycle_labels, title = "Variables", bty = "n")
```

## Critical Hysteresis

```{r}
# set plot margins
par(mar = c(5, 5, 5, 7), xpd = TRUE)

# select data
hyst2_data <- data %>%
  filter(pp_nr == 768) 

# get changepoint locations
hyst2_cpts <- cpt_res[[769]]@cpts

# plot variables across time and set basic settings
plot(x = 0:40319, y = hyst2_data$sui_thoughts, type = "l", xlab = "Time in Minutes", 
     ylab = "Value",main = "Hysteresis 2 (Simulation 769)", las = 1, cex.axis = 0.75, 
     bty = "l", ylim = c(0, max(hyst2_data$stressor)))
abline(v = hyst2_cpts, col = "tomato", xpd = FALSE)
lines(hyst2_data$stressor, col = "deepskyblue")
lines(hyst2_data$av_state, col = "darkviolet")
lines(hyst2_data$other_escape, col = "chartreuse")

# add legend
legend("topright", inset = c(-0.31, 0.2), lty = 1, cex = 0.6, col = cycle_cols, 
       legend = cycle_labels, title = "Variables", bty = "n")
```

## Convergence and Limit Cycle

```{r}
# set plot margins
par(mar = c(5, 5, 5, 7), xpd = TRUE)

# select data
conv_data <- data %>%
  filter(pp_nr == 258) 

# get changepoint locations
conv_cpts <- cpt_res[[259]]@cpts

# plot variables across time and set basic settings
plot(x = 0:40319, y = conv_data$sui_thoughts, type = "l", lwd = 2, xlab = "Time in Minutes", 
     ylab = "Value",main = "Limit Cycle with Convergent Value (Simulation 259)", las = 1, cex.axis = 0.75, 
     bty = "l", ylim = c(0, max(conv_data$sui_thoughts)))
abline(v = conv_cpts, col = "tomato", xpd = FALSE, lwd = 2)
lines(conv_data$stressor, col = "deepskyblue")
lines(conv_data$av_state, col = "darkviolet")
lines(conv_data$other_escape, col = "chartreuse")

# add legend
legend("topright", inset = c(-0.31, 0.2), lty = 1, cex = 0.6, col = cycle_cols, 
       legend = cycle_labels, title = "Variables", bty = "n", lwd = 2)
```

## Buffered

```{r}
# set plot margins
par(mar = c(5, 5, 5, 7), xpd = TRUE)

# select data
fp_data <- data %>%
  filter(pp_nr == 850) 

# get changepoint locations
fp_cpts <- cpt_res[[851]]@cpts

# plot variables across time and set basic settings
plot(x = 0:40319, y = fp_data$sui_thoughts, type = "l", xlab = "Time in Minutes", 
     ylab = "Value",main = "Buffered (Simulation 851)", las = 1, cex.axis = 0.75, 
     bty = "l", ylim = c(0, max(fp_data$stressor)))
abline(v = fp_cpts, col = "tomato", xpd = FALSE)
lines(fp_data$stressor, col = "deepskyblue")
lines(fp_data$av_state, col = "darkviolet")
lines(fp_data$other_escape, col = "chartreuse")

# add legend
legend("topright", inset = c(-0.31, 0.2), lty = 1, cex = 0.6, col = cycle_cols, 
       legend = cycle_labels, title = "Variables", bty = "n")
```
